[phases.setup]
nixPkgs = ["curl", "unzip"]

[phases.build]
cmds = [
  "curl -L https://github.com/static-web-server/static-web-server/releases/download/v2.34.0/static-web-server-x86_64-unknown-linux-gnu.zip -o sws.zip",
  "unzip sws.zip -d ./sws-bin",
  "chmod +x ./sws-bin/static-web-server"
]

[start]
cmd = "./sws-bin/static-web-server --port $PORT --root . --default-file porto.html"
